services:

  # Spring Boot Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SPRING_PROFILES_ACTIVE=local
      - DATABASE_URL=jdbc:postgresql://db:5432/creditmanagement
      - DATABASE_USERNAME=user
      - DATABASE_PASSWORD=1234
      - DATABASE_DRIVER=org.postgresql.Driver
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - JPA_HIBERNATE_DDL_AUTO=update
      - JPA_SHOW_SQL=false
      - JPA_FORMAT_SQL=true
      - JPA_HIBERNATE_DIALECT=org.hibernate.dialect.PostgreSQLDialect
      - PERSON_SEED_ENABLED=false
      - PERSON_COUNT=20
      - PHONE_NUMBER_PER_PERSON=2
    ports:
      - "8080:8080"
    depends_on:
      - db
      - redis
      - keycloak
    networks:
      - app-network
    restart: unless-stopped

  # PostgreSQL Database
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=creditmanagement
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app-network
    ports:
      - "5432:5432"
    restart: unless-stopped

  # Redis
  redis:
    image: redis:latest
    volumes:
      - redis_data:/data
    networks:
      - app-network
    ports:
        - "6379:6379"
    restart: unless-stopped

  # Keycloak
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    environment:
      KC_HOSTNAME: localhost
      KC_HOSTNAME_PORT: 8081
      KC_HOSTNAME_STRICT_BACKCHANNEL: "true"
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HEALTH_ENABLED: "true"
      KC_LOG_LEVEL: info
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8081/health/ready" ]
      interval: 15s
      timeout: 2s
      retries: 15
    command: ["start-dev", "--http-port", "7080"]
    volumes:
      - keycloak:/opt/keycloak/data/
    ports:
      - "8081:8081"
    networks:
        - app-network

# Volumes to persist database data
volumes:
  db_data:
  redis_data:
  keycloak:

# Networks for communication
networks:
  app-network:
    driver: bridge