# Database Configuration
spring.datasource:
  url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/creditmanagement?reWriteBatchedInserts=true}
  username: ${DATABASE_USERNAME:postgres}
  password: ${DATABASE_PASSWORD:1234}
  driver-class-name: ${DATABASE_DRIVER:org.postgresql.Driver}

# JPA Configuration
spring.jpa:
  hibernate.ddl-auto: ${JPA_HIBERNATE_DDL_AUTO:update}
  show-sql: ${JPA_SHOW_SQL:false}
  properties:
    hibernate:
      dialect: ${JPA_HIBERNATE_DIALECT:org.hibernate.dialect.PostgreSQLDialect}

# Seeders Configuration
person-seeder:
  enabled: ${PERSON_SEED_ENABLED:false}
  person-count: ${PERSON_COUNT:200}
  phone-number-per-person: ${PHONE_NUMBER_PER_PERSON:2}

# Server Error Configuration
server.error:
  include-stacktrace: ${INCLUDE_STACKTRACE:NEVER}
  include-message: ${INCLUDE_MESSAGE:ALWAYS}
