# Database Configuration
spring.datasource:
  url: ${DATABASE_URL}
  username: ${DATABASE_USERNAME}
  password: ${DATABASE_PASSWORD}
  driver-class-name: ${DATABASE_DRIVER}

# Redis configuration
spring.data.redis:
  host: ${REDIS_HOST}
  port: ${REDIS_PORT}

# JPA Configuration
spring.jpa:
  hibernate.ddl-auto: ${JPA_HIBERNATE_DDL_AUTO}
  show-sql: ${JPA_SHOW_SQL}
  properties:
    hibernate:
      dialect: ${JPA_HIBERNATE_DIALECT}

# Server Error Configuration
server.error:
  include-stacktrace: ${INCLUDE_STACKTRACE:NEVER}
  include-message: ${INCLUDE_MESSAGE:NEVER}