# Database Configuration
spring.datasource:
  url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/creditmanagement?reWriteBatchedInserts=true}
  username: ${DATABASE_USERNAME:user}
  password: ${DATABASE_PASSWORD:1234}
  driver-class-name: ${DATABASE_DRIVER:org.postgresql.Driver}

# Redis configuration
spring.data.redis:
  host: ${REDIS_HOST:localhost}
  port: ${REDIS_PORT:6379}

# JPA Configuration
spring.jpa:
  hibernate.ddl-auto: ${JPA_HIBERNATE_DDL_AUTO:update}
  show-sql: ${JPA_SHOW_SQL:false}
  properties:
    hibernate:
      format_sql : ${JPA_FORMAT_SQL:true}
      dialect: ${JPA_HIBERNATE_DIALECT:org.hibernate.dialect.PostgreSQLDialect}

# Logger Configuration
logging.level:
  org:
    hibernate:
      SQL: DEBUG
      type.descriptor.sql.BasicBinder: TRACE
      orm.jdbc.bind: TRACE
    springframework:
      data.*.*: trace
      cache.*: trace
  com.saadmeddiche.creditmanagement:
    services.PersonDataCreator: DEBUG

# Seeders Configuration
person-seeder:
  enabled: ${PERSON_SEED_ENABLED:false}
  person-count: ${PERSON_COUNT:50000}
  phone-number-per-person: ${PHONE_NUMBER_PER_PERSON:2}
  credit-per-person: ${CREDIT_PER_PERSON:2}

# Server Error Configuration
server.error:
  include-stacktrace: ${INCLUDE_STACKTRACE:NEVER}
  include-message: ${INCLUDE_MESSAGE:ALWAYS}

# docker run --rm -it -p 5000:80 -p 2525:25 rnwood/smtp4dev
# SMTP Configuration
spring.mail:
  host: ${MAIL_HOST:localhost}
  port: ${MAIL_PORT:2525}
  username: ${MAIL_USERNAME:TEST}
  password: ${MAIL_PASSWORD:TEST}
  properties.mail:
    debug: ${MAIL_DEBUG:false}
    transport.protocol: ${MAIL_TRANSPORT_PROTOCOL:smtp}
    smtp.auth: ${MAIL_SMTP_AUTH:false}
    smtp.connectiontimeout: ${MAIL_SMTP_CONNECTION_TIMEOUT:5000}
    smtp.timeout: ${MAIL_SMTP_TIMEOUT:5000}
    smtp.writetimeout: ${MAIL_SMTP_WRITE_TIMEOUT:5000}
    smtp.starttls.enable: ${MAIL_SMTP_STARTTLS_ENABLE:true}

# Custom Static Resources Configuration
custom-static-resource:
  location: ${CUSTOM_STATIC_RESOURCE_LOCATION:/files}