# Database Configuration
spring.datasource:
  url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/creditmanagement?reWriteBatchedInserts=true}
  username: ${DATABASE_USERNAME:user}
  password: ${DATABASE_PASSWORD:1234}
  driver-class-name: ${DATABASE_DRIVER:org.postgresql.Driver}

# Redis configuration
spring.data.redis:
  host: ${REDIS_HOST:localhost}
  port: ${REDIS_PORT:6379}

# JPA Configuration
spring.jpa:
  hibernate.ddl-auto: ${JPA_HIBERNATE_DDL_AUTO:update}
  show-sql: ${JPA_SHOW_SQL:false}
  properties:
    hibernate:
      format_sql : ${JPA_FORMAT_SQL:true}
      dialect: ${JPA_HIBERNATE_DIALECT:org.hibernate.dialect.PostgreSQLDialect}

# Logger Configuration
logging.level.org:
  hibernate:
    SQL: DEBUG
    type.descriptor.sql.BasicBinder: TRACE
    orm.jdbc.bind: TRACE
  springframework:
    data.*.*: trace
    cache.*: trace

# Seeders Configuration
person-seeder:
  enabled: ${PERSON_SEED_ENABLED:false}
  person-count: ${PERSON_COUNT:200000}
  phone-number-per-person: ${PHONE_NUMBER_PER_PERSON:1}

# Server Error Configuration
server.error:
  include-stacktrace: ${INCLUDE_STACKTRACE:NEVER}
  include-message: ${INCLUDE_MESSAGE:ALWAYS}
